import { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "motion/react";

const EASE = [0.16, 1, 0.3, 1] as const;

interface Deck {
  id: string;
  name: string;
  tagline: string;
  slides: string[];
}

const DECKS: Deck[] = [
  {
    id: "ps5",
    name: "PlayStation 5",
    tagline: "Product launch · bold & cinematic",
    slides: [
      "/samples/ps5/ps51.webp",
      "/samples/ps5/ps52.webp",
      "/samples/ps5/ps53.webp",
      "/samples/ps5/ps54.webp",
    ],
  },
  {
    id: "iphone18",
    name: "iPhone 18 Concept",
    tagline: "Concept reveal · premium",
    slides: [
      "/samples/iphone18/iphone181.webp",
      "/samples/iphone18/iphone182.webp",
      "/samples/iphone18/iphone183.webp",
      "/samples/iphone18/iphone184.webp",
    ],
  },
  {
    id: "macbook",
    name: "MacBook Air",
    tagline: "Product page · clean & airy",
    slides: [
      "/samples/mac/mac1.webp",
      "/samples/mac/mac2.webp",
      "/samples/mac/mac3.webp",
      "/samples/mac/mac4.webp",
    ],
  },
  {
    id: "future",
    name: "Future Shock",
    tagline: "Editorial · collage explainer",
    slides: [
      "/samples/future/future1.webp",
      "/samples/future/future2.webp",
      "/samples/future/future3.webp",
      "/samples/future/future4.webp",
    ],
  },
  {
    id: "iphone17",
    name: "iPhone 17",
    tagline: "Product launch · clean & premium",
    slides: [
      "/samples/iphone/iphone1.webp",
      "/samples/iphone/iphone2.webp",
      "/samples/iphone/iphone3.webp",
      "/samples/iphone/iphone4.webp",
    ],
  },
];

export function DeckShowcase() {
  const [deckIdx, setDeckIdx] = useState(0);
  const [slideIdx, setSlideIdx] = useState(0);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);
  const deck = DECKS[deckIdx];

  const stop = () => {
    if (timer.current) clearInterval(timer.current);
    timer.current = null;
  };
  const start = () => {
    stop();
    timer.current = setInterval(
      () => setSlideIdx((s) => (s + 1) % DECKS[deckIdx].slides.length),
      3600
    );
  };
  useEffect(() => {
    start();
    return stop;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [deckIdx]);

  const selectDeck = (i: number) => {
    if (i === deckIdx) return;
    setDeckIdx(i);
    setSlideIdx(0);
  };
  const selectSlide = (i: number) => {
    setSlideIdx(i);
    start();
  };

  return (
    <section id="output" className="relative px-4 py-24 sm:py-28">
      <div className="mx-auto max-w-6xl">
        {/* ---- header ---- */}
        <div className="mb-12 text-center">
          <motion.h2
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.65, ease: EASE }}
            className="font-display font-display-tight text-[clamp(2.6rem,6vw,4.8rem)] leading-[1.02] text-white"
          >
            Real decks. Zero templates.
          </motion.h2>
          <motion.p
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="mx-auto mt-5 max-w-lg text-[17px] leading-relaxed text-white/55"
          >
            Every slide here was generated by Moonshot. Pick a brand and flip
            through the deck yourself.
          </motion.p>
        </div>

        {/* ---- deck tabs ---- */}
        <div className="mb-7 flex flex-wrap items-center justify-center gap-1.5">
          {DECKS.map((d, i) => {
            const active = i === deckIdx;
            return (
              <button
                key={d.id}
                type="button"
                onMouseEnter={() => selectDeck(i)}
                onFocus={() => selectDeck(i)}
                onClick={() => selectDeck(i)}
                className="relative rounded-full px-4 py-2 text-sm font-medium transition-colors"
              >
                {active && (
                  <motion.span
                    layoutId="deck-tab"
                    className="absolute inset-0 rounded-full border border-white/12 bg-white/[0.08]"
                    transition={{ type: "spring", stiffness: 380, damping: 32 }}
                  />
                )}
                <span
                  className={`relative ${active ? "text-white" : "text-white/45 hover:text-white/75"}`}
                >
                  {d.name}
                </span>
              </button>
            );
          })}
        </div>

        {/* ---- stage ---- */}
        <div className="[perspective:1800px]">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-60px" }}
            transition={{ duration: 0.7, ease: EASE }}
            className="ms-glass relative overflow-hidden rounded-[24px] p-2 shadow-[0_50px_140px_-30px_rgba(0,0,0,0.85)]"
          >
            <div className="relative aspect-video w-full overflow-hidden rounded-[18px]">
              <AnimatePresence initial={false} mode="popLayout">
                <motion.img
                  key={deck.id + slideIdx}
                  src={deck.slides[slideIdx]}
                  alt={`${deck.name} — slide ${slideIdx + 1}`}
                  initial={{ opacity: 0, scale: 1.03 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 0.6, ease: EASE }}
                  className="absolute inset-0 size-full object-cover"
                />
              </AnimatePresence>

              {/* caption */}
              <div className="pointer-events-none absolute inset-x-0 bottom-0 flex items-end justify-between gap-4 bg-gradient-to-t from-black/60 via-black/10 to-transparent p-5 pt-16">
                <div>
                  <div className="text-[15px] font-semibold text-white drop-shadow">
                    {deck.name}
                  </div>
                  <div className="text-xs text-white/65 drop-shadow">{deck.tagline}</div>
                </div>
                {/* slide pips */}
                <div className="flex gap-1.5">
                  {deck.slides.map((_, i) => (
                    <span
                      key={i}
                      className={`h-1 rounded-full transition-all duration-300 ${
                        i === slideIdx ? "w-5 bg-white" : "w-1.5 bg-white/40"
                      }`}
                    />
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        </div>

        {/* ---- thumbnail strip ---- */}
        <div className="mx-auto mt-5 flex max-w-xl items-center justify-center gap-3">
          {deck.slides.map((src, i) => (
            <button
              key={src}
              type="button"
              onClick={() => selectSlide(i)}
              className={`relative w-24 overflow-hidden rounded-lg border bg-black/40 transition-all sm:w-28 ${
                i === slideIdx
                  ? "border-white/60 ring-1 ring-white/30"
                  : "border-white/10 opacity-55 hover:opacity-90"
              }`}
              aria-label={`Show ${deck.name} slide ${i + 1}`}
            >
              <img
                src={src}
                alt=""
                loading="lazy"
                className="aspect-video w-full object-cover"
              />
            </button>
          ))}
        </div>
      </div>
    </section>
  );
}
